name: Test Push
permissions:
  contents: write
on:
  push:
    branches:
      - main
jobs:
  run-task:
    runs-on: ubuntu-latest
    
    steps:
      - name: Проверка кода
        uses: actions/checkout@v2

      - name: Создание файла
        run: |
          mkdir ./destination
          ./gen.sh

      - name: Настройка Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Коммит изменений
        run: |
          git add .
          git commit -m "Добавлен сгенерированный файл" || echo "Нет изменений для коммита"

      - name: Отправка изменений
        run: git push origin main