name: Test Push
on:
  push:
    
jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка пути
        run: |
          echo "Run workflow"
          pwd > patch.txt
      - name: Запуск тестов
        run: echo $PWD > patch1.txt
      - name: Выполнение команды
        run: |
          echo $PWD
          echo "Этот шаг выполняется по графику!"
